"""rename budget to expense

Revision ID: 04e345914c21
Revises: a5e9eb387461
Create Date: 2026-04-09 17:44:51.823037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e345914c21'
down_revision: Union[str, Sequence[str], None] = 'a5e9eb387461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ACCOMMODATION', 'TRANSPORT', 'ACTIVITIES', 'FOOD', 'SHOPPING', 'EXTRAS', name='expensecategory'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('budgets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('ACCOMMODATION', 'TRANSPORT', 'ACTIVITIES', 'FOOD', 'SHOPPING', 'EXTRAS', name='budgetcategory'), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_estimated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('actual_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('budgets_trip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('budgets_pkey'))
    )
    op.drop_table('expenses')
    # ### end Alembic commands ###
