"""add cascade delete to all foreign keys

Revision ID: 0a13482c93bf
Revises: 04e345914c21
Create Date: 2026-04-09 18:19:24.413831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a13482c93bf'
down_revision: Union[str, Sequence[str], None] = '04e345914c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accommodations_trip_id_fkey'), 'accommodations', type_='foreignkey')
    op.create_foreign_key(None, 'accommodations', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('activities_day_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'days', ['day_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('days_trip_id_fkey'), 'days', type_='foreignkey')
    op.create_foreign_key(None, 'days', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('expenses_trip_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('flights_trip_id_fkey'), 'flights', type_='foreignkey')
    op.create_foreign_key(None, 'flights', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('packing_items_trip_id_fkey'), 'packing_items', type_='foreignkey')
    op.create_foreign_key(None, 'packing_items', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transports_trip_id_fkey'), 'transports', type_='foreignkey')
    op.create_foreign_key(None, 'transports', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transports', type_='foreignkey')
    op.create_foreign_key(op.f('transports_trip_id_fkey'), 'transports', 'trips', ['trip_id'], ['id'])
    op.drop_constraint(None, 'packing_items', type_='foreignkey')
    op.create_foreign_key(op.f('packing_items_trip_id_fkey'), 'packing_items', 'trips', ['trip_id'], ['id'])
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.create_foreign_key(op.f('flights_trip_id_fkey'), 'flights', 'trips', ['trip_id'], ['id'])
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_trip_id_fkey'), 'expenses', 'trips', ['trip_id'], ['id'])
    op.drop_constraint(None, 'days', type_='foreignkey')
    op.create_foreign_key(op.f('days_trip_id_fkey'), 'days', 'trips', ['trip_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_day_id_fkey'), 'activities', 'days', ['day_id'], ['id'])
    op.drop_constraint(None, 'accommodations', type_='foreignkey')
    op.create_foreign_key(op.f('accommodations_trip_id_fkey'), 'accommodations', 'trips', ['trip_id'], ['id'])
    # ### end Alembic commands ###
