"""remove day table and update activities

Revision ID: 0eef9bb2a2fc
Revises: b257ff14248a
Create Date: 2026-04-10 21:54:32.185406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eef9bb2a2fc'
down_revision: Union[str, Sequence[str], None] = 'b257ff14248a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
def upgrade() -> None:
    # 1 — prima rimuovi la FK che dipende da days
    op.drop_constraint('activities_day_id_fkey', 'activities', type_='foreignkey')
    
    # 2 — rimuovi day_id da activities
    op.drop_column('activities', 'day_id')
    
    # 3 — ora puoi droppare days
    op.drop_table('days')
    
    # 4 — aggiungi trip_id ad activities
    op.add_column('activities', sa.Column('trip_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'activities', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    
    # 5 — aggiungi activity_date
    op.add_column('activities', sa.Column('activity_date', sa.Date(), nullable=True))
    
    # 6 — aggiungi notes a trips
    op.add_column('trips', sa.Column('notes', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'notes')
    op.add_column('activities', sa.Column('day_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_day_id_fkey'), 'activities', 'days', ['day_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'activity_date')
    op.drop_column('activities', 'trip_id')
    op.create_table('days',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('days_trip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('days_pkey'))
    )
    # ### end Alembic commands ###
