"""dates for trip must be non Nullabe

Revision ID: 89b9b9bf49a7
Revises: f3c4d5e6f7g8
Create Date: 2026-04-12 11:13:42.325901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b9b9bf49a7'
down_revision: Union[str, Sequence[str], None] = 'f3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # First, delete any rows with NULL trip_id from related tables
    op.execute("DELETE FROM activities WHERE trip_id IS NULL")
    op.execute("DELETE FROM flights WHERE trip_id IS NULL")
    op.execute("DELETE FROM accommodations WHERE trip_id IS NULL")
    op.execute("DELETE FROM transports WHERE trip_id IS NULL")
    op.execute("DELETE FROM expenses WHERE trip_id IS NULL")
    op.execute("DELETE FROM packing_items WHERE trip_id IS NULL")
    
    # Now set trip_id and date fields to NOT NULL
    op.alter_column('activities', 'trip_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('trips', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('trips', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('trips', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('activities', 'trip_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
