"""update activity and flight fields

Revision ID: 8c3633db6db8
Revises: 0a13482c93bf
Create Date: 2026-04-09 22:29:28.285696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c3633db6db8'
down_revision: Union[str, Sequence[str], None] = '0a13482c93bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('flights', sa.Column('origin', sa.String(length=10), nullable=False))
    op.add_column('flights', sa.Column('destination', sa.String(length=10), nullable=False))
    op.add_column('flights', sa.Column('departure_time', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('arrival_time', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('airline', sa.String(length=255), nullable=True))
    op.add_column('flights', sa.Column('booking_reference', sa.String(length=50), nullable=True))
    op.add_column('flights', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('flights', 'arrival_airport')
    op.drop_column('flights', 'arrival_datetime')
    op.drop_column('flights', 'company')
    op.drop_column('flights', 'departure_datetime')
    op.drop_column('flights', 'departure_airport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_airport', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('departure_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('arrival_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('arrival_airport', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('flights', 'notes')
    op.drop_column('flights', 'booking_reference')
    op.drop_column('flights', 'airline')
    op.drop_column('flights', 'arrival_time')
    op.drop_column('flights', 'departure_time')
    op.drop_column('flights', 'destination')
    op.drop_column('flights', 'origin')
    op.alter_column('activities', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
