"""initial

Revision ID: 93dbb38abf1a
Revises: 
Create Date: 2026-04-09 13:26:43.493910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93dbb38abf1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HOTEL', 'HOSTEL', 'AIRBNB', 'LODGE', 'CAMPING', 'RESORT', 'APARTMENT', 'EXTRAS', name='accommodationtype'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('checkin_date', sa.Date(), nullable=True),
    sa.Column('checkout_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'TO_BOOK', 'BOOKED', 'CANCELLED', 'COMPLETED', name='status'), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pay_method', sa.String(length=255), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ACCOMMODATION', 'TRANSPORT', 'ACTIVITIES', 'FOOD', 'SHOPPING', 'EXTRAS', name='budgetcategory'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('departure_airport', sa.String(length=10), nullable=True),
    sa.Column('arrival_airport', sa.String(length=10), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(), nullable=True),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('baggage_included', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'TO_BOOK', 'BOOKED', 'CANCELLED', 'COMPLETED', name='status'), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pay_method', sa.String(length=255), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DOCUMENTS', 'CLOTHING', 'MEDICINE', 'TECHNOLOGY', 'EXTRAS', name='packingcategory'), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('TRAIN', 'BUS', 'CAR', 'SHUTTLE', 'FERRY', 'TAXI', name='transporttype'), nullable=True),
    sa.Column('departure_location', sa.String(length=255), nullable=True),
    sa.Column('arrival_location', sa.String(length=255), nullable=True),
    sa.Column('departure_datetime', sa.DateTime(), nullable=True),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'TO_BOOK', 'BOOKED', 'CANCELLED', 'COMPLETED', name='status'), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pay_method', sa.String(length=255), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('extra_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'TO_BOOK', 'BOOKED', 'CANCELLED', 'COMPLETED', name='status'), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('pay_method', sa.String(length=255), nullable=True),
    sa.Column('cancellation_date', sa.Date(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('transports')
    op.drop_table('packing_items')
    op.drop_table('flights')
    op.drop_table('days')
    op.drop_table('budgets')
    op.drop_table('accommodations')
    op.drop_table('trips')
    # ### end Alembic commands ###
