"""day_date not nullable

Revision ID: a5e9eb387461
Revises: 93dbb38abf1a
Create Date: 2026-04-09 15:14:32.649787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e9eb387461'
down_revision: Union[str, Sequence[str], None] = '93dbb38abf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('days', 'day_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('days', 'day_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
