"""update transportations fields

Revision ID: b257ff14248a
Revises: e917a4643eec
Create Date: 2026-04-09 23:35:35.334223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b257ff14248a'
down_revision: Union[str, Sequence[str], None] = 'e917a4643eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'origin',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('flights', 'destination',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('transports', sa.Column('transport_type', sa.Enum('TRAIN', 'BUS', 'CAR', 'SHUTTLE', 'FERRY', 'TAXI', 'OTHER', name='transporttype'), nullable=False))
    op.add_column('transports', sa.Column('origin', sa.String(length=255), nullable=False))
    op.add_column('transports', sa.Column('destination', sa.String(length=255), nullable=False))
    op.add_column('transports', sa.Column('departure_time', sa.DateTime(), nullable=True))
    op.add_column('transports', sa.Column('arrival_time', sa.DateTime(), nullable=True))
    op.add_column('transports', sa.Column('operator', sa.String(length=255), nullable=True))
    op.add_column('transports', sa.Column('booking_reference', sa.String(length=50), nullable=True))
    op.drop_column('transports', 'arrival_datetime')
    op.drop_column('transports', 'type')
    op.drop_column('transports', 'departure_location')
    op.drop_column('transports', 'arrival_location')
    op.drop_column('transports', 'departure_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transports', sa.Column('departure_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('arrival_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('departure_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('type', postgresql.ENUM('TRAIN', 'BUS', 'CAR', 'SHUTTLE', 'FERRY', 'TAXI', name='transporttype'), autoincrement=False, nullable=True))
    op.add_column('transports', sa.Column('arrival_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transports', 'booking_reference')
    op.drop_column('transports', 'operator')
    op.drop_column('transports', 'arrival_time')
    op.drop_column('transports', 'departure_time')
    op.drop_column('transports', 'destination')
    op.drop_column('transports', 'origin')
    op.drop_column('transports', 'transport_type')
    op.alter_column('flights', 'destination',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('flights', 'origin',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
