"""update expenses fields

Revision ID: e917a4643eec
Revises: fb463794284a
Create Date: 2026-04-09 23:21:30.430592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e917a4643eec'
down_revision: Union[str, Sequence[str], None] = 'fb463794284a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('expenses', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'notes')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
