"""update accommodations fields

Revision ID: fb463794284a
Revises: 8c3633db6db8
Create Date: 2026-04-09 23:03:07.198742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb463794284a'
down_revision: Union[str, Sequence[str], None] = '8c3633db6db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('accommodation_type', sa.Enum('HOTEL', 'HOSTEL', 'AIRBNB', 'LODGE', 'CAMPING', 'RESORT', 'APARTMENT', 'OTHER', name='accommodationtype'), nullable=True))
    op.add_column('accommodations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('accommodations', sa.Column('check_in', sa.Date(), nullable=True))
    op.add_column('accommodations', sa.Column('check_out', sa.Date(), nullable=True))
    op.add_column('accommodations', sa.Column('cost_per_night', sa.Float(), nullable=True))
    op.add_column('accommodations', sa.Column('booking_reference', sa.String(length=50), nullable=True))
    op.alter_column('accommodations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('accommodations', 'checkout_date')
    op.drop_column('accommodations', 'type')
    op.drop_column('accommodations', 'cost')
    op.drop_column('accommodations', 'checkin_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('checkin_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('accommodations', sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('accommodations', sa.Column('type', postgresql.ENUM('HOTEL', 'HOSTEL', 'AIRBNB', 'LODGE', 'CAMPING', 'RESORT', 'APARTMENT', 'EXTRAS', name='accommodationtype'), autoincrement=False, nullable=True))
    op.add_column('accommodations', sa.Column('checkout_date', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('accommodations', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('accommodations', 'booking_reference')
    op.drop_column('accommodations', 'cost_per_night')
    op.drop_column('accommodations', 'check_out')
    op.drop_column('accommodations', 'check_in')
    op.drop_column('accommodations', 'address')
    op.drop_column('accommodations', 'accommodation_type')
    # ### end Alembic commands ###
